# Week 1

## Print

In [1]:
println("Hello world!")

Hello world!


In [2]:
println(4+3, " evaluated")

7 evaluated


In [3]:
println("Hello!" * " My word!")

Hello! My word!


In [4]:
println("Hello!" * " My word!"^3)

Hello! My word! My word! My word!


In [5]:
?print

search: print println printstyled sprint isprint prevind parentindices precision



```
print([io::IO], xs...)
```

Write to `io` (or to the default output stream [`stdout`](@ref) if `io` is not given) a canonical (un-decorated) text representation. The representation used by `print` includes minimal formatting and tries to avoid Julia-specific details.

`print` falls back to calling `show`, so most types should just define `show`. Define `print` if your type has a separate "plain" representation. For example, `show` displays strings with quotes, and `print` displays strings without quotes.

[`string`](@ref) returns the output of `print` as a string.

# Examples

```jldoctest
julia> print("Hello World!")
Hello World!
julia> io = IOBuffer();

julia> print(io, "Hello", ' ', :World!)

julia> String(take!(io))
"Hello World!"
```


# Arithmetical expressions

* Parentheses > exponentiation > multiplication or division (left to right) > addition and subtraction (left to right)

* Just exponentiation is from right to left

In [6]:
3^2^3

6561

# Logical expressions
* `!` is the NOT operator
* `&&` is the AND operator
* `||` is the OR operator

In [7]:
!true

false

In [8]:
true && true

true

In [9]:
true && false


false

In [11]:
true || true

true

In [12]:
true || false

true

In [13]:
1 < 22


true

In [14]:
-10 > 3

false

In [15]:
2 == 4-2

true

In [17]:
# precedence is from left to right
3-4 > 1 && 2+2==4 || 10-5 > 2

true

In [18]:
(3-4> 1) && (2+2==4) || (10-5>2)

true

In [19]:
false && true || true

true

In [20]:
5040/60

84.0

In [21]:
3x²-2x+3

LoadError: UndefVarError: x² not defined

In [23]:
3 & 5 > 0

true

In [24]:
8 & 5 > 0

false

& is a bitwise 'and' operator and is evaluated first. With a bitwise operation Julia transforms 3 and 5 into binary and executes a bitwise 'and'. Thus 3 \&& 5 returns binary 1 which translates to 1 and this is bigger than 0 and thus true. However, 8 \&& 5 in binary would return 0 which translates to False. Thus 8 \&& 5 > 0 is false.

In [25]:
a=true
b=!!!!a
b

true

# Julia's type system

In [26]:
typeof(1)

Int64

In [27]:
typeof(1+3+5)

Int64

In [28]:
typeof("Hello world!")

String

In [30]:
typeof("δβγα")

String

In [31]:
typeof("H")

String

In [32]:
typeof('H')

Char

In [33]:
typeof(1+3+5.)

Float64

In [34]:
typeof('Hello')

LoadError: syntax: character literal contains multiple characters

a string is a sequence of characters

In [37]:
println("⋄") #\diamond \diamondsuit

⋄


In [38]:
typeof(true)

Bool

In [39]:
2.0 == 2

true

In [42]:
# diff types
2.0 === 2

false

Every type (abstract type) has a subtype

Real has Int64 and Float64

# Variables


# Functions

In [1]:
greeting = "Hello, world!"
println(greeting)

Hello, world!


In [4]:
a, b, c = cos(0.2), log(10), abs(-1.22)

(0.9800665778412416, 2.302585092994046, 1.22)

In [5]:
a

0.9800665778412416

In [6]:
? cos

search: cos cosh cosd cosc cospi acos acosh acosd sincos sincosd const close



```
cos(x)
```

Compute cosine of `x`, where `x` is in radians.

---

```
cos(A::AbstractMatrix)
```

Compute the matrix cosine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the cosine. Otherwise, the cosine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> cos(fill(1.0, (2,2)))
2×2 Array{Float64,2}:
  0.291927  -0.708073
 -0.708073   0.291927
```


In [7]:
?help

search: help schedule Channel hasfield @threadcall AbstractChannel



**Welcome to Julia 1.5.0.** The full manual is available at

```
https://docs.julialang.org
```

as well as many great tutorials and learning resources:

```
https://julialang.org/learning/
```

For help on a specific function or macro, type `?` followed by its name, e.g. `?cos`, or `?@time`, and press enter. Type `;` to enter shell mode, `]` to enter package mode.


In [8]:
? floor

search: floor OverflowError StackOverflowError



```
floor([T,] x)
floor(x; digits::Integer= [, base = 10])
floor(x; sigdigits::Integer= [, base = 10])
```

`floor(x)` returns the nearest integral value of the same type as `x` that is less than or equal to `x`.

`floor(T, x)` converts the result to type `T`, throwing an `InexactError` if the value is not representable.

`digits`, `sigdigits` and `base` work as for [`round`](@ref).

---

```
floor(x::Period, precision::T) where T <: Union{TimePeriod, Week, Day} -> T
```

Round `x` down to the nearest multiple of `precision`. If `x` and `precision` are different subtypes of `Period`, the return value will have the same type as `precision`.

For convenience, `precision` may be a type instead of a value: `floor(x, Dates.Hour)` is a shortcut for `floor(x, Dates.Hour(1))`.

```jldoctest
julia> floor(Dates.Day(16), Dates.Week)
2 weeks

julia> floor(Dates.Minute(44), Dates.Minute(15))
30 minutes

julia> floor(Dates.Hour(36), Dates.Day)
1 day
```

Rounding to a `precision` of `Month`s or `Year`s is not supported, as these `Period`s are of inconsistent length.

---

```
floor(dt::TimeType, p::Period) -> TimeType
```

Return the nearest `Date` or `DateTime` less than or equal to `dt` at resolution `p`.

For convenience, `p` may be a type instead of a value: `floor(dt, Dates.Hour)` is a shortcut for `floor(dt, Dates.Hour(1))`.

```jldoctest
julia> floor(Date(1985, 8, 16), Dates.Month)
1985-08-01

julia> floor(DateTime(2013, 2, 13, 0, 31, 20), Dates.Minute(15))
2013-02-13T00:30:00

julia> floor(DateTime(2016, 8, 6, 12, 0, 0), Dates.Day)
2016-08-06T00:00:00
```


In [9]:
methods(muladd)

# 12 methods for generic function "muladd":
[1] muladd(a::Float16, b::Float16, c::Float16) in Base at float.jl:411
[2] muladd(x::Float64, y::Float64, z::Float64) in Base at float.jl:410
[3] muladd(x::Float32, y::Float32, z::Float32) in Base at float.jl:409
[4] muladd(z::Complex, w::Complex, x::Complex) in Base at complex.jl:280
[5] muladd(x::Real, z::Complex, y::Number) in Base at complex.jl:323
[6] muladd(z::Complex, x::Real, y::Real) in Base at complex.jl:324
[7] muladd(z::Complex, x::Real, w::Complex) in Base at complex.jl:325
[8] muladd(x::Real, y::Real, z::Complex) in Base at complex.jl:327
[9] muladd(z::Complex, w::Complex, x::Real) in Base at complex.jl:328
[10] muladd(x::T, y::T, z::T) where T<:Number in Base at promotion.jl:392
[11] muladd(x::Number, y::Number, z::Number) in Base at promotion.jl:346
[12] muladd(x, y, z) in Base.Math at math.jl:1137

In [10]:
 myfunc(firstvar) = 20*firstvar

myfunc (generic function with 1 method)

In [11]:
myfunc(333.2222)

6664.4439999999995

In [12]:
addxtoy(x,y) = x+y

addxtoy (generic function with 1 method)

In [13]:
addxtoy(33, -22.2)

10.8

In [14]:
function nextfunc(a, b, c)
    a*b + c
    
end


nextfunc (generic function with 1 method)

In [15]:
nextfunc(7,5,3)

38

In [16]:
function showdebugprintln(testvar)
    println("inside the showdebugprint() now")
    println("the type of testvar is $(typeof(testvar)) and the value of testvar is $testvar")
end


showdebugprintln (generic function with 1 method)

In [17]:
a = ['1', 2.]
showdebugprintln(a)

inside the showdebugprint() now
the type of testvar is Array{Any,1} and the value of testvar is Any['1', 2.0]


In [18]:
mycos(x) = cos(x)

mycos (generic function with 1 method)

In [19]:
mycos(.7)

0.7648421872844885

In [20]:
mycos(adj, hyp) = adj/hyp

mycos (generic function with 2 methods)

In [21]:
mycos(12, 13)

0.9230769230769231

In [22]:
methods(mycos)

# 2 methods for generic function "mycos":
[1] mycos(x) in Main at In[18]:1
[2] mycos(adj, hyp) in Main at In[20]:1

In [23]:
mycos(thet::Float64) = cos(thet)

mycos (generic function with 3 methods)

In [24]:
mycos(thet::Float64) = cos(thet)
mycos(hyp, adj) = adj/hyp

mycos (generic function with 3 methods)

In [25]:
mycos(1)

0.5403023058681398

In [29]:
?\

search: \



```
\(x, y)
```

Left division operator: multiplication of `y` by the inverse of `x` on the left. Gives floating-point results for integer arguments.

# Examples

```jldoctest
julia> 3 \ 6
2.0

julia> inv(3) * 6
2.0

julia> A = [4 3; 2 1]; x = [5, 6];

julia> A \ x
2-element Array{Float64,1}:
  6.5
 -7.0

julia> inv(A) * x
2-element Array{Float64,1}:
  6.5
 -7.0
```

---

```
\(A, B)
```

Matrix division using a polyalgorithm. For input matrices `A` and `B`, the result `X` is such that `A*X == B` when `A` is square. The solver that is used depends upon the structure of `A`.  If `A` is upper or lower triangular (or diagonal), no factorization of `A` is required and the system is solved with either forward or backward substitution. For non-triangular square matrices, an LU factorization is used.

For rectangular `A` the result is the minimum-norm least squares solution computed by a pivoted QR factorization of `A` and a rank estimate of `A` based on the R factor.

When `A` is sparse, a similar polyalgorithm is used. For indefinite matrices, the `LDLt` factorization does not use pivoting during the numerical factorization and therefore the procedure can fail even for invertible matrices.

# Examples

```jldoctest
julia> A = [1 0; 1 -2]; B = [32; -4];

julia> X = A \ B
2-element Array{Float64,1}:
 32.0
 18.0

julia> A * X == B
true
```

---

```
(\)(F::QRSparse, B::StridedVecOrMat)
```

Solve the least squares problem $\min\|Ax - b\|^2$ or the linear system of equations $Ax=b$ when `F` is the sparse QR factorization of $A$. A basic solution is returned when the problem is underdetermined.

# Examples

```jldoctest
julia> A = sparse([1,2,4], [1,1,1], [1.0,1.0,1.0], 4, 2)
4×2 SparseMatrixCSC{Float64,Int64} with 3 stored entries:
  [1, 1]  =  1.0
  [2, 1]  =  1.0
  [4, 1]  =  1.0

julia> qr(A)\fill(1.0, 4)
2-element Array{Float64,1}:
 1.0
 0.0
```


In [27]:
60 \ 5040

84.0

In [28]:
60 / 5040

0.011904761904761904

In [30]:
5040 / 60

84.0

In [31]:
a,b=1,2

a,b=b,a
a

2

In [32]:
function test(input)
  println("$input"^2)
end

test(2)

22


In [33]:
println(add2(5, 7))

LoadError: UndefVarError: add2 not defined

In [34]:
add2(x,y) = return x+y
add2(5,7)

12

In [35]:
function coordinates(x, y=0, z=0)
  println("($x, $y, $z)")
end

coordinates (generic function with 3 methods)

In [36]:
coordinates(1,2)

(1, 2, 0)


In [37]:
coordinates(1,0,2)

(1, 0, 2)


In [38]:
coordinates(1,0)

(1, 0, 0)


In [39]:
coordinates(1,0,0)

(1, 0, 0)


In [40]:
println("$(2*6)")

12


In [41]:
2^3^2-500

12

In [42]:
2^2^1^5+2^3

12

In [43]:
(2^3)^2-500

-436

In [44]:
5 - 7 * 2 + 4

-5

In [47]:
(5 - 7) * 2 + 4

0

In [48]:
1 + 3 < 5 && 2^2 === 4.0

false

In [53]:
x = 7
(x ≥ 5.0) && (x < 7.0)

false

In [54]:
true && false && false || true

true

In [55]:
((true && false) && false) || true

true

In [56]:
(true && false) && (false || true)

false

In [57]:
true && ((false && false) || true)

true

In [58]:
true && (false && (false || true))

false

In [59]:
matrix = Array{Float64,2}(undef, a, b)

2×1 Array{Float64,2}:
 0.0
 5.0e-324

In [60]:
matrix = Array{Float64,2}(undef, 2, 3
)

2×3 Array{Float64,2}:
 6.89967e-310  6.89969e-310    6.7583e-320
 6.89969e-310  6.89969e-310  NaN

In [61]:
data = [1.6800483  -1.641695388; 
        0.501309281 -0.977697538; 
        1.528012113 0.52771122;
        1.70012253 1.711524991; 
        1.992493625 1.891000015;
        2.706075824 -0.463427794;
        2.994931927 -0.443566619;
        3.491852811 -1.275179133;
        3.501191722 -0.690499597;
        4.459924502 -5.516130799;
        4.936965851 -6.001703074;
        5.023289852 -8.36416901;
        5.04233698 -7.924477517;
        5.50739285 -10.77482371;
        5.568665171 -10.9171878]

15×2 Array{Float64,2}:
 1.68005    -1.6417
 0.501309   -0.977698
 1.52801     0.527711
 1.70012     1.71152
 1.99249     1.891
 2.70608    -0.463428
 2.99493    -0.443567
 3.49185    -1.27518
 3.50119    -0.6905
 4.45992    -5.51613
 4.93697    -6.0017
 5.02329    -8.36417
 5.04234    -7.92448
 5.50739   -10.7748
 5.56867   -10.9172

In [63]:
data[:,1]

15-element Array{Float64,1}:
 1.6800483
 0.501309281
 1.528012113
 1.70012253
 1.992493625
 2.706075824
 2.994931927
 3.491852811
 3.501191722
 4.459924502
 4.936965851
 5.023289852
 5.04233698
 5.50739285
 5.568665171

In [80]:
function coordinates(x, y, z)
  # if x == y == z == 0 # yes
  # if x == 0 & y == 0 & z == 0 # no
  # if x ===0.0 && y===0.0 && z===0.0 # no
  # if x==0 && y==0 && x==z # yes
  # if x=0 & y=0 & z=0 # no
  if x==0 && z==0 && y==0
    println("origin")
  else
    println("($x, $y, $z)")
  end
end

coordinates (generic function with 3 methods)

In [81]:
coordinates(0,0,2)

(0, 0, 2)


In [82]:
coordinates(0,0,0)

origin


In [83]:
a, b = 2, 3           
function f(x)  
  b = 5 
  a*x + b
end
f(7), b

(19, 3)

In [84]:
function f(x)
  return 2x
  3x
end

f (generic function with 1 method)

In [85]:
f(5)

10